spring:
  application:
  name: user-service

jwt:
  public-key: ${JWT_PUBLIC_KEY_PATH:classpath:certs/public.key}
  private-key: ${JWT_PRIVATE_KEY_PATH:classpath:certs/private.key}
  jwk-key: chave-jwk #temporario e sera convertido como variavel de ambiente
  expires-access: 3600
  expires-refresh: 86400
  expires-refresh-long: 604800